# Generated by Django 4.2.11 on 2025-01-17 13:33

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_balance_currency_transaction_amount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=14, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
