# Generated by Django 4.2.11 on 2025-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
