# Generated by Django 5.2.9 on 2026-01-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_account_owner_account_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
